version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "weekly"
