# Pull base image
FROM node:latest

# Set work directory
WORKDIR /code

# Copy package files first to leverage Docker cache
COPY package*.json ./
RUN npm install


# Copy the rest of the source code
COPY . .

EXPOSE 3000
